### ISSUE TITLE
Warning: Error in system2: '"git"' not found

### ISSUE THREAD

**Issue by sbr2567** [ColumbusCollaboratory/photon#10]
I know this most likely isn't an issue with the package. The first time I ran the package I didn't get this error. However I've started to now get this error. It seems that photon isn't finding git on my system? I reinstalled git, restarted R and still get the same error.

The error occurs the moment I try to run the package with "create job". It occurs before anything is created with the package. Any advice on what this might be? I've been looking for a solid week for a package that can compile shiny, this is my last resort so hopefully I can get this working.

Thank you.

**Comment by aarizvi** [comment]
Are you using mac or windows?

Can you send me `sessionInfo()`

**Comment by sbr2567** [comment]
Sorry windows. Sure do you just need the console?

**Comment by aarizvi** [comment]
So if you go to powershell or the linux emulator on Windows and typed in:

```
git --version
node -v
npm -v
```

All of three of those commands work?

**Comment by sbr2567** [comment]
**Here's the console**
> photon::photon_rstudioaddin()
Loading required namespace: miniUI
Loading required namespace: shinyFiles
Loading required package: shiny

Listening on {my ip address}
Running Photon
The directory is D:/ShinyDtest/Test1
Warning: Error in system2: '"git"' not found
  76: system2
  75: photon::startFun
  74: observeEventHandler
   3: shiny::runApp
   2: shiny::runGadget
   1: photon::photon_rstudioaddin

**Results from powershell**

PS C:\Users\srb> git --version
git version 2.26.1.windows.1

PS C:\Users\srb> node -v
v12.16.2

PS C:\Users\srb> npm -v
6.14.4

**Session Info**

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0 shiny_1.4.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  magrittr_1.5     xtable_1.8-4     R6_2.4.1         rlang_0.4.5      fastmap_1.0.1    fansi_0.4.1     
 [9] tools_3.6.3      packrat_0.5.0    photon_0.0.1     miniUI_0.1.1.1   cli_2.0.2        htmltools_0.4.0  shinyFiles_0.8.0 ellipsis_0.3.0  
[17] assertthat_0.2.1 digest_0.6.25    tibble_3.0.0     lifecycle_0.2.0  crayon_1.3.4     later_1.0.0      vctrs_0.2.4      promises_1.1.0  
[25] fs_1.4.1         rsconnect_0.8.16 glue_1.4.0       mime_0.9         stringi_1.4.6    pillar_1.4.3     compiler_3.6.3   jsonlite_1.6.1  
[33] httpuv_1.5.2     pkgconfig_2.0.3

**Comment by sbr2567** [comment]
Interesting. I restarted my computer and tried to run the package again. This time it's a different error. Any ideas what would be causing this?

> photon::photon_rstudioaddin()
Loading required namespace: miniUI
Loading required namespace: shinyFiles
Loading required package: shiny

Listening on {my ip}
Running Photon
The directory is D:/ShinyDtest/Test1
Warning in system2("git", args = c("clone https://github.com/ColumbusCollaboratory/electron-quick-start",  :
  running command '"git" clone https://github.com/ColumbusCollaboratory/electron-quick-start D:/ShinyDtest/Test1' had status 129
'D:/ShinyDtest' is not recognized as an internal or external command,
operable program or batch file.
Warning in shell(sprintf("%s/R.exe --file=%s/install_packages.R -q --slave --args cran_packages %s github_packages %s bioc_packages %s",  :
  'D:/ShinyDtest/Test1/electron-quick-start/R-Portable-Win/bin/R.exe --file=D:/ShinyDtest/Test1/electron-quick-start/R-Portable-Win/bin/install_packages.R -q --slave --args cran_packages mgcv,matrixStats github_packages thomasp85/patchwork bioc_packages SummarizedExperiemnt,VariantAnnotation' execution failed with error code 1
The directory name is invalid.
Warning in shell(sprintf("cd %s && npm install", electron_win_dir)) :
  'cd D:/ShinyDtest/Test1\electron-quick-start && npm install' execution failed with error code 1
The directory name is invalid.
Warning in shell(sprintf("cd %s && npm run package-win", electron_win_dir)) :
  'cd D:/ShinyDtest/Test1\electron-quick-start && npm run package-win' execution failed with error code 1
