### ISSUE TITLE
photon addin does not select directory

### ISSUE THREAD

**Issue by wasimaftab** [ColumbusCollaboratory/photon#19]
photon:::photon_rstudioaddin() does not select directory.
I have made a  [small video](http://shorturl.at/eklnB) of my operation.
Here are my platform details:

    platform       x86_64-w64-mingw32
    arch           x86_64
    os             mingw32
    system         x86_64, mingw32
    status
    major          4
    minor          0.0
    year           2020
    month          04
    day            24
    svn rev        78286
    language       R
    version.string R version 4.0.0 (2020-04-24)
    nickname       Arbor Day

**Comment by aarizvi** [comment]
@wasimaftab Can you put that video on youtube. That link isn't working.

**Comment by wasimaftab** [comment]
> @wasimaftab Can you put that video on youtube. That link isn't working.
Done!
https://www.youtube.com/watch?v=G2rrZdd6FDo

**Comment by aarizvi** [comment]
@wasimaftab Is it possible that you haven't scrolled all the way down to the "Select" button?

See screenshot below:

![image](https://user-images.githubusercontent.com/11141478/83063671-82b41080-a02e-11ea-8063-5b5c6268fb14.png)

**Comment by wasimaftab** [comment]
@aarizvi Thanks for pointing my mistake. However, there are other issues for which I will open a new ticket.
