### ISSUE TITLE
'shinyFiles' package is required

### ISSUE THREAD

**Issue by md0u80c9** [ColumbusCollaboratory/photon#2]
Hi,

I installed Photon today to play with.

When I installed it all installed successfully.

Clicking on the Add-in, I received a message that shinyFiles was not found.

This is easily solved - I installed the shinyFiles package from CRAN. But I suspect shinyFiles should be in the imports for the DESCRIPTION file for the package.

**Comment by aarizvi** [comment]
Added shinyFiles to DESCRIPTION
