### ISSUE TITLE
Suggestion: locally compiled packages

### ISSUE THREAD

**Issue by md0u80c9** [ColumbusCollaboratory/photon#3]
Hi,

In addition to supporting GitHub packages, it would be very helpful if the add in could support local packages: ie providing a path for the package that can be built locally.

This may be very helpful in data analysis environments where internet access is not permitted (and of course solves the github issue indirectly since GitHub packages can be downloaded and built locally where a local package may not necessary be uploadable to GitHub).

**Comment by petegordon** [comment]
You can go into the command line R-Portable-Win/bin/R and run the local directory R instance and install any package you'd like.  This is how you can install local packages in the the local directory library.  But, sorry, you are correct can't do that through the Add-in.

https://github.com/ColumbusCollaboratory/electron-quick-start/tree/master/R-Portable-Mac/library
https://github.com/ColumbusCollaboratory/electron-quick-start/tree/master/R-Portable-Win/library
