### ISSUE TITLE
ShinyBS dependency

### ISSUE THREAD

**Issue by ksgremes** [ColumbusCollaboratory/photon#34]
On a fresh install of R and RStudio, after installing the package (from github), the dependency "ShinyBS" is not automatically installed

**Comment by nikolkj** [comment]
I think this is a R 4.0.5 compatibility issue with ShinyBS; ran into this message and reverted back to R 4.0.2 -- no issue afterwards. Was able to install the ShinyBS package successfully. Looks like you just have to use a previous version of R until ShinyBS is updated.

**Comment by ksgremes** [comment]
Closed as this is not related to the package itself
